#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_CrmVSSolution.Common.Models
{
	
	
	/// <summary>
	/// Information about team membership type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum team_membershiptype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Membersandguests = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Members = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owners = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Guests = 3,
	}
	
	/// <summary>
	/// Information about team type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum team_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owner = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Access = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SecurityGroup = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OfficeGroup = 3,
	}
	
	/// <summary>
	/// Collection of system users that routinely collaborate. Teams can be used to simplify record sharing and provide team members with common access to organization data when team members belong to different Business Units.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("team")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class Team : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the team entity
		/// </summary>
		public partial class Fields
		{
			public const string AdministratorId = "administratorid";
			public const string AdministratorIdName = "administratoridname";
			public const string AdministratorIdYomiName = "administratoridyominame";
			public const string AzureActiveDirectoryObjectId = "azureactivedirectoryobjectid";
			public const string BusinessUnitId = "businessunitid";
			public const string BusinessUnitIdName = "businessunitidname";
			public const string cm_Province = "cm_province";
			public const string cm_ProvinceName = "cm_provincename";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string DelegatedAuthorizationId = "delegatedauthorizationid";
			public const string DelegatedAuthorizationIdName = "delegatedauthorizationidname";
			public const string Description = "description";
			public const string EMailAddress = "emailaddress";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IsDefault = "isdefault";
			public const string IsDefaultName = "isdefaultname";
			public const string IsSasTokenSet = "issastokenset";
			public const string issastokensetName = "issastokensetname";
			public const string MembershipType = "membershiptype";
			public const string membershiptypeName = "membershiptypename";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string Name = "name";
			public const string OrganizationId = "organizationid";
			public const string OrganizationIdName = "organizationidname";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string ProcessId = "processid";
			public const string QueueId = "queueid";
			public const string QueueIdName = "queueidname";
			public const string RegardingObjectId = "regardingobjectid";
			public const string ShareLinkQualifier = "sharelinkqualifier";
			public const string StageId = "stageid";
			public const string SystemManaged = "systemmanaged";
			public const string SystemManagedName = "systemmanagedname";
			public const string TeamId = "teamid";
			public const string Id = "teamid";
			public const string TeamTemplateId = "teamtemplateid";
			public const string TeamType = "teamtype";
			public const string TeamTypeName = "teamtypename";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TransactionCurrencyIdName = "transactioncurrencyidname";
			public const string TraversedPath = "traversedpath";
			public const string VersionNumber = "versionnumber";
			public const string YomiName = "yominame";
			public const string cm_programassociation_Program_team = "cm_programassociation_Program_team";
			public const string lead_owning_team = "lead_owning_team";
			public const string team_accounts = "team_accounts";
			public const string team_cm_programassociation = "team_cm_programassociation";
			public const string team_cm_province = "team_cm_province";
			public const string team_connections1 = "team_connections1";
			public const string team_connections2 = "team_connections2";
			public const string team_contacts = "team_contacts";
			public const string team_opportunities = "team_opportunities";
			public const string team_orders = "team_orders";
			public const string cm_Team_cm_Province_cm_Province = "cm_Team_cm_Province_cm_Province";
			public const string opportunity_Teams = "opportunity_Teams";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Team() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "team";
		
		public const string EntityLogicalCollectionName = "teams";
		
		public const string EntitySetName = "teams";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user primary responsible for the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("administratorid")]
		public Microsoft.Xrm.Sdk.EntityReference AdministratorId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("administratorid");
			}
			set
			{
				this.OnPropertyChanging("AdministratorId");
				this.SetAttributeValue("administratorid", value);
				this.OnPropertyChanged("AdministratorId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("administratoridname")]
		public string AdministratorIdName
		{
			get
			{
				if (this.FormattedValues.Contains("administratorid"))
				{
					return this.FormattedValues["administratorid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("administratoridyominame")]
		public string AdministratorIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("administratorid"))
				{
					return this.FormattedValues["administratorid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The object Id for a group.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("azureactivedirectoryobjectid")]
		public System.Nullable<System.Guid> AzureActiveDirectoryObjectId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("azureactivedirectoryobjectid");
			}
			set
			{
				this.OnPropertyChanging("AzureActiveDirectoryObjectId");
				this.SetAttributeValue("azureactivedirectoryobjectid", value);
				this.OnPropertyChanged("AzureActiveDirectoryObjectId");
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit with which the team is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		public Microsoft.Xrm.Sdk.EntityReference BusinessUnitId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("businessunitid");
			}
			set
			{
				this.OnPropertyChanging("BusinessUnitId");
				this.SetAttributeValue("businessunitid", value);
				this.OnPropertyChanged("BusinessUnitId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitidname")]
		public string BusinessUnitIdName
		{
			get
			{
				if (this.FormattedValues.Contains("businessunitid"))
				{
					return this.FormattedValues["businessunitid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_province")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Province
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_province");
			}
			set
			{
				this.OnPropertyChanging("cm_Province");
				this.SetAttributeValue("cm_province", value);
				this.OnPropertyChanged("cm_Province");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_provincename")]
		public string cm_ProvinceName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_province"))
				{
					return this.FormattedValues["cm_province"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the team was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The delegated authorization context for the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("delegatedauthorizationid")]
		public Microsoft.Xrm.Sdk.EntityReference DelegatedAuthorizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("delegatedauthorizationid");
			}
			set
			{
				this.OnPropertyChanging("DelegatedAuthorizationId");
				this.SetAttributeValue("delegatedauthorizationid", value);
				this.OnPropertyChanged("DelegatedAuthorizationId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("delegatedauthorizationidname")]
		public string DelegatedAuthorizationIdName
		{
			get
			{
				if (this.FormattedValues.Contains("delegatedauthorizationid"))
				{
					return this.FormattedValues["delegatedauthorizationid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Description of the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// Email address for the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
		public string EMailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("emailaddress");
			}
			set
			{
				this.OnPropertyChanging("EMailAddress");
				this.SetAttributeValue("emailaddress", value);
				this.OnPropertyChanged("EMailAddress");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the team with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Unique identifier of the data import or data migration that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Information about whether the team is a default business unit team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdefault")]
		public System.Nullable<bool> IsDefault
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdefault");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdefaultname")]
		public string IsDefaultName
		{
			get
			{
				if (this.FormattedValues.Contains("isdefault"))
				{
					return this.FormattedValues["isdefault"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("issastokenset")]
		public System.Nullable<bool> IsSasTokenSet
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("issastokenset");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("issastokensetname")]
		public string issastokensetName
		{
			get
			{
				if (this.FormattedValues.Contains("issastokenset"))
				{
					return this.FormattedValues["issastokenset"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("membershiptype")]
		public virtual team_membershiptype? MembershipType
		{
			get
			{
				return ((team_membershiptype?)(EntityOptionSetEnum.GetEnum(this, "membershiptype")));
			}
			set
			{
				this.OnPropertyChanging("MembershipType");
				this.SetAttributeValue("membershiptype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("MembershipType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("membershiptypename")]
		public string membershiptypeName
		{
			get
			{
				if (this.FormattedValues.Contains("membershiptype"))
				{
					return this.FormattedValues["membershiptype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who last modified the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the team was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who last modified the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Name of the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Unique identifier of the organization associated with the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public System.Nullable<System.Guid> OrganizationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("organizationid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationidname")]
		public string OrganizationIdName
		{
			get
			{
				if (this.FormattedValues.Contains("organizationid"))
				{
					return this.FormattedValues["organizationid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Shows the ID of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.OnPropertyChanging("ProcessId");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("ProcessId");
			}
		}
		
		/// <summary>
		/// Unique identifier of the default queue for the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueid")]
		public Microsoft.Xrm.Sdk.EntityReference QueueId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("queueid");
			}
			set
			{
				this.OnPropertyChanging("QueueId");
				this.SetAttributeValue("queueid", value);
				this.OnPropertyChanged("QueueId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueidname")]
		public string QueueIdName
		{
			get
			{
				if (this.FormattedValues.Contains("queueid"))
				{
					return this.FormattedValues["queueid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Choose the record that the team relates to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		public Microsoft.Xrm.Sdk.EntityReference RegardingObjectId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("regardingobjectid");
			}
			set
			{
				this.OnPropertyChanging("RegardingObjectId");
				this.SetAttributeValue("regardingobjectid", value);
				this.OnPropertyChanged("RegardingObjectId");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sharelinkqualifier")]
		public string ShareLinkQualifier
		{
			get
			{
				return this.GetAttributeValue<string>("sharelinkqualifier");
			}
		}
		
		/// <summary>
		/// Shows the ID of the stage.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.OnPropertyChanging("StageId");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("StageId");
			}
		}
		
		/// <summary>
		/// Select whether the team will be managed by the system.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemmanaged")]
		public System.Nullable<bool> SystemManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("systemmanaged");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemmanagedname")]
		public string SystemManagedName
		{
			get
			{
				if (this.FormattedValues.Contains("systemmanaged"))
				{
					return this.FormattedValues["systemmanaged"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamid")]
		public System.Nullable<System.Guid> TeamId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("teamid");
			}
			set
			{
				this.OnPropertyChanging("TeamId");
				this.SetAttributeValue("teamid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("TeamId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.TeamId = value;
			}
		}
		
		/// <summary>
		/// Shows the team template that is associated with the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamtemplateid")]
		public Microsoft.Xrm.Sdk.EntityReference TeamTemplateId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("teamtemplateid");
			}
			set
			{
				this.OnPropertyChanging("TeamTemplateId");
				this.SetAttributeValue("teamtemplateid", value);
				this.OnPropertyChanged("TeamTemplateId");
			}
		}
		
		/// <summary>
		/// Select the team type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamtype")]
		public virtual team_type? TeamType
		{
			get
			{
				return ((team_type?)(EntityOptionSetEnum.GetEnum(this, "teamtype")));
			}
			set
			{
				this.OnPropertyChanging("TeamType");
				this.SetAttributeValue("teamtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("TeamType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("teamtypename")]
		public string TeamTypeName
		{
			get
			{
				if (this.FormattedValues.Contains("teamtype"))
				{
					return this.FormattedValues["teamtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyidname")]
		public string TransactionCurrencyIdName
		{
			get
			{
				if (this.FormattedValues.Contains("transactioncurrencyid"))
				{
					return this.FormattedValues["transactioncurrencyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.OnPropertyChanging("TraversedPath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("TraversedPath");
			}
		}
		
		/// <summary>
		/// Version number of the team.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Pronunciation of the full name of the team, written in phonetic hiragana or katakana characters.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("yominame")]
		public string YomiName
		{
			get
			{
				return this.GetAttributeValue<string>("yominame");
			}
			set
			{
				this.OnPropertyChanging("YomiName");
				this.SetAttributeValue("yominame", value);
				this.OnPropertyChanged("YomiName");
			}
		}
		
		/// <summary>
		/// 1:N cm_programassociation_Program_team
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_programassociation_Program_team")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.cm_ProgramAssociation> cm_programassociation_Program_team
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.cm_ProgramAssociation>("cm_programassociation_Program_team", null);
			}
			set
			{
				this.OnPropertyChanging("cm_programassociation_Program_team");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.cm_ProgramAssociation>("cm_programassociation_Program_team", null, value);
				this.OnPropertyChanged("cm_programassociation_Program_team");
			}
		}
		
		/// <summary>
		/// 1:N lead_owning_team
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lead_owning_team")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.Lead> lead_owning_team
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.Lead>("lead_owning_team", null);
			}
			set
			{
				this.OnPropertyChanging("lead_owning_team");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.Lead>("lead_owning_team", null, value);
				this.OnPropertyChanged("lead_owning_team");
			}
		}
		
		/// <summary>
		/// 1:N team_accounts
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_accounts")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.Account> team_accounts
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.Account>("team_accounts", null);
			}
			set
			{
				this.OnPropertyChanging("team_accounts");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.Account>("team_accounts", null, value);
				this.OnPropertyChanged("team_accounts");
			}
		}
		
		/// <summary>
		/// 1:N team_cm_programassociation
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_cm_programassociation")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.cm_ProgramAssociation> team_cm_programassociation
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.cm_ProgramAssociation>("team_cm_programassociation", null);
			}
			set
			{
				this.OnPropertyChanging("team_cm_programassociation");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.cm_ProgramAssociation>("team_cm_programassociation", null, value);
				this.OnPropertyChanged("team_cm_programassociation");
			}
		}
		
		/// <summary>
		/// 1:N team_cm_province
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_cm_province")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.cm_Province> team_cm_province
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.cm_Province>("team_cm_province", null);
			}
			set
			{
				this.OnPropertyChanging("team_cm_province");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.cm_Province>("team_cm_province", null, value);
				this.OnPropertyChanged("team_cm_province");
			}
		}
		
		/// <summary>
		/// 1:N team_connections1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_connections1")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.Connection> team_connections1
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.Connection>("team_connections1", null);
			}
			set
			{
				this.OnPropertyChanging("team_connections1");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.Connection>("team_connections1", null, value);
				this.OnPropertyChanged("team_connections1");
			}
		}
		
		/// <summary>
		/// 1:N team_connections2
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_connections2")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.Connection> team_connections2
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.Connection>("team_connections2", null);
			}
			set
			{
				this.OnPropertyChanging("team_connections2");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.Connection>("team_connections2", null, value);
				this.OnPropertyChanged("team_connections2");
			}
		}
		
		/// <summary>
		/// 1:N team_contacts
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_contacts")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.Contact> team_contacts
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.Contact>("team_contacts", null);
			}
			set
			{
				this.OnPropertyChanging("team_contacts");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.Contact>("team_contacts", null, value);
				this.OnPropertyChanged("team_contacts");
			}
		}
		
		/// <summary>
		/// 1:N team_opportunities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_opportunities")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.Opportunity> team_opportunities
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.Opportunity>("team_opportunities", null);
			}
			set
			{
				this.OnPropertyChanging("team_opportunities");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.Opportunity>("team_opportunities", null, value);
				this.OnPropertyChanged("team_opportunities");
			}
		}
		
		/// <summary>
		/// 1:N team_orders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_orders")]
		public System.Collections.Generic.IEnumerable<CM_CrmVSSolution.Common.Models.SalesOrder> team_orders
		{
			get
			{
				return this.GetRelatedEntities<CM_CrmVSSolution.Common.Models.SalesOrder>("team_orders", null);
			}
			set
			{
				this.OnPropertyChanging("team_orders");
				this.SetRelatedEntities<CM_CrmVSSolution.Common.Models.SalesOrder>("team_orders", null, value);
				this.OnPropertyChanged("team_orders");
			}
		}
		
		/// <summary>
		/// N:1 cm_Team_cm_Province_cm_Province
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_province")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_Team_cm_Province_cm_Province")]
		public CM_CrmVSSolution.Common.Models.cm_Province cm_Team_cm_Province_cm_Province
		{
			get
			{
				return this.GetRelatedEntity<CM_CrmVSSolution.Common.Models.cm_Province>("cm_Team_cm_Province_cm_Province", null);
			}
			set
			{
				this.OnPropertyChanging("cm_Team_cm_Province_cm_Province");
				this.SetRelatedEntity<CM_CrmVSSolution.Common.Models.cm_Province>("cm_Team_cm_Province_cm_Province", null, value);
				this.OnPropertyChanged("cm_Team_cm_Province_cm_Province");
			}
		}
		
		/// <summary>
		/// N:1 opportunity_Teams
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opportunity_Teams")]
		public CM_CrmVSSolution.Common.Models.Opportunity opportunity_Teams
		{
			get
			{
				return this.GetRelatedEntity<CM_CrmVSSolution.Common.Models.Opportunity>("opportunity_Teams", null);
			}
			set
			{
				this.OnPropertyChanging("opportunity_Teams");
				this.SetRelatedEntity<CM_CrmVSSolution.Common.Models.Opportunity>("opportunity_Teams", null, value);
				this.OnPropertyChanged("opportunity_Teams");
			}
		}
	}
}
#pragma warning restore CS1591
