#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum cm_propertytypeoptions
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CurbsideResidence = 121540000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MultiFamilyDwelling = 121540001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DepotLocation = 121540002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SchoolSite = 121540003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ParkSite = 121540004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampgroundSite = 121540005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LongTermCareLocation = 121540006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RetirementHome = 121540007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonEligibleSource = 121540008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 121540009,
	}
}
#pragma warning restore CS1591
