#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Models
{
	
	
	/// <summary>
	/// The sales process stage that this entity is in.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum opportunity_salesstage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Develop = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Propose = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Close = 3,
	}
}
#pragma warning restore CS1591
