#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Models
{
	
	
	/// <summary>
	/// Status of the Checklist Master
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum cm_checklistmaster_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Checklist Master
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum cm_checklistmaster_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cm_checklistmaster")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class cm_ChecklistMaster : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the cm_checklistmaster entity
		/// </summary>
		public partial class Fields
		{
			public const string cm_CaseCategory = "cm_casecategory";
			public const string cm_CaseCategoryName = "cm_casecategoryname";
			public const string cm_CaseSubCategory = "cm_casesubcategory";
			public const string cm_CaseSubCategoryName = "cm_casesubcategoryname";
			public const string cm_ChecklistMasterId = "cm_checklistmasterid";
			public const string Id = "cm_checklistmasterid";
			public const string cm_ChecklistValidationRequired = "cm_checklistvalidationrequired";
			public const string cm_checklistvalidationrequiredName = "cm_checklistvalidationrequiredname";
			public const string cm_Name = "cm_name";
			public const string cm_PopulateSurveyInvite = "cm_populatesurveyinvite";
			public const string cm_populatesurveyinviteName = "cm_populatesurveyinvitename";
			public const string cm_Program = "cm_program";
			public const string cm_ProgramName = "cm_programname";
			public const string cm_ProgramYomiName = "cm_programyominame";
			public const string cm_Survey = "cm_survey";
			public const string cm_SurveyName = "cm_surveyname";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string cm_casechecklistcatalog_ChecklistMaster_cm_checklistmaster = "cm_casechecklistcatalog_ChecklistMaster_cm_checklistmaster";
			public const string cm_checklistmaster_CaseCategory_cm_casecategory = "cm_checklistmaster_CaseCategory_cm_casecategory";
			public const string cm_checklistmaster_CaseSubCategory_cm_casesubcategory = "cm_checklistmaster_CaseSubCategory_cm_casesubcategory";
			public const string cm_checklistmaster_Program_team = "cm_checklistmaster_Program_team";
			public const string cm_checklistmaster_Survey_msfp_survey = "cm_checklistmaster_Survey_msfp_survey";
			public const string team_cm_checklistmaster = "team_cm_checklistmaster";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public cm_ChecklistMaster() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "cm_checklistmaster";
		
		public const string EntityLogicalCollectionName = "cm_checklistmasters";
		
		public const string EntitySetName = "cm_checklistmasters";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casecategory")]
		public Microsoft.Xrm.Sdk.EntityReference cm_CaseCategory
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_casecategory");
			}
			set
			{
				this.OnPropertyChanging("cm_CaseCategory");
				this.SetAttributeValue("cm_casecategory", value);
				this.OnPropertyChanged("cm_CaseCategory");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casecategoryname")]
		public string cm_CaseCategoryName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_casecategory"))
				{
					return this.FormattedValues["cm_casecategory"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casesubcategory")]
		public Microsoft.Xrm.Sdk.EntityReference cm_CaseSubCategory
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_casesubcategory");
			}
			set
			{
				this.OnPropertyChanging("cm_CaseSubCategory");
				this.SetAttributeValue("cm_casesubcategory", value);
				this.OnPropertyChanged("cm_CaseSubCategory");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casesubcategoryname")]
		public string cm_CaseSubCategoryName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_casesubcategory"))
				{
					return this.FormattedValues["cm_casesubcategory"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_checklistmasterid")]
		public System.Nullable<System.Guid> cm_ChecklistMasterId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("cm_checklistmasterid");
			}
			set
			{
				this.OnPropertyChanging("cm_ChecklistMasterId");
				this.SetAttributeValue("cm_checklistmasterid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("cm_ChecklistMasterId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_checklistmasterid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.cm_ChecklistMasterId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_checklistvalidationrequired")]
		public System.Nullable<bool> cm_ChecklistValidationRequired
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cm_checklistvalidationrequired");
			}
			set
			{
				this.OnPropertyChanging("cm_ChecklistValidationRequired");
				this.SetAttributeValue("cm_checklistvalidationrequired", value);
				this.OnPropertyChanged("cm_ChecklistValidationRequired");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_checklistvalidationrequiredname")]
		public string cm_checklistvalidationrequiredName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_checklistvalidationrequired"))
				{
					return this.FormattedValues["cm_checklistvalidationrequired"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_name")]
		public string cm_Name
		{
			get
			{
				return this.GetAttributeValue<string>("cm_name");
			}
			set
			{
				this.OnPropertyChanging("cm_Name");
				this.SetAttributeValue("cm_name", value);
				this.OnPropertyChanged("cm_Name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_populatesurveyinvite")]
		public System.Nullable<bool> cm_PopulateSurveyInvite
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cm_populatesurveyinvite");
			}
			set
			{
				this.OnPropertyChanging("cm_PopulateSurveyInvite");
				this.SetAttributeValue("cm_populatesurveyinvite", value);
				this.OnPropertyChanged("cm_PopulateSurveyInvite");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_populatesurveyinvitename")]
		public string cm_populatesurveyinviteName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_populatesurveyinvite"))
				{
					return this.FormattedValues["cm_populatesurveyinvite"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_program")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Program
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_program");
			}
			set
			{
				this.OnPropertyChanging("cm_Program");
				this.SetAttributeValue("cm_program", value);
				this.OnPropertyChanged("cm_Program");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_programname")]
		public string cm_ProgramName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_program"))
				{
					return this.FormattedValues["cm_program"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_programyominame")]
		public string cm_ProgramYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_program"))
				{
					return this.FormattedValues["cm_program"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_survey")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Survey
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_survey");
			}
			set
			{
				this.OnPropertyChanging("cm_Survey");
				this.SetAttributeValue("cm_survey", value);
				this.OnPropertyChanged("cm_Survey");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_surveyname")]
		public string cm_SurveyName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_survey"))
				{
					return this.FormattedValues["cm_survey"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Checklist Master
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual cm_checklistmaster_statecode? statecode
		{
			get
			{
				return ((cm_checklistmaster_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Checklist Master
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual cm_checklistmaster_statuscode? statuscode
		{
			get
			{
				return ((cm_checklistmaster_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N cm_casechecklistcatalog_ChecklistMaster_cm_checklistmaster
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_casechecklistcatalog_ChecklistMaster_cm_checklistmaster")]
		public System.Collections.Generic.IEnumerable<Plugins.Models.cm_CaseChecklistCatalog> cm_casechecklistcatalog_ChecklistMaster_cm_checklistmaster
		{
			get
			{
				return this.GetRelatedEntities<Plugins.Models.cm_CaseChecklistCatalog>("cm_casechecklistcatalog_ChecklistMaster_cm_checklistmaster", null);
			}
			set
			{
				this.OnPropertyChanging("cm_casechecklistcatalog_ChecklistMaster_cm_checklistmaster");
				this.SetRelatedEntities<Plugins.Models.cm_CaseChecklistCatalog>("cm_casechecklistcatalog_ChecklistMaster_cm_checklistmaster", null, value);
				this.OnPropertyChanged("cm_casechecklistcatalog_ChecklistMaster_cm_checklistmaster");
			}
		}
		
		/// <summary>
		/// N:1 cm_checklistmaster_CaseCategory_cm_casecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casecategory")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_checklistmaster_CaseCategory_cm_casecategory")]
		public Plugins.Models.cm_CaseCategory cm_checklistmaster_CaseCategory_cm_casecategory
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.cm_CaseCategory>("cm_checklistmaster_CaseCategory_cm_casecategory", null);
			}
			set
			{
				this.OnPropertyChanging("cm_checklistmaster_CaseCategory_cm_casecategory");
				this.SetRelatedEntity<Plugins.Models.cm_CaseCategory>("cm_checklistmaster_CaseCategory_cm_casecategory", null, value);
				this.OnPropertyChanged("cm_checklistmaster_CaseCategory_cm_casecategory");
			}
		}
		
		/// <summary>
		/// N:1 cm_checklistmaster_CaseSubCategory_cm_casesubcategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casesubcategory")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_checklistmaster_CaseSubCategory_cm_casesubcategory")]
		public Plugins.Models.cm_CaseSubCategory cm_checklistmaster_CaseSubCategory_cm_casesubcategory
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.cm_CaseSubCategory>("cm_checklistmaster_CaseSubCategory_cm_casesubcategory", null);
			}
			set
			{
				this.OnPropertyChanging("cm_checklistmaster_CaseSubCategory_cm_casesubcategory");
				this.SetRelatedEntity<Plugins.Models.cm_CaseSubCategory>("cm_checklistmaster_CaseSubCategory_cm_casesubcategory", null, value);
				this.OnPropertyChanged("cm_checklistmaster_CaseSubCategory_cm_casesubcategory");
			}
		}
		
		/// <summary>
		/// N:1 cm_checklistmaster_Program_team
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_program")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_checklistmaster_Program_team")]
		public Plugins.Models.Team cm_checklistmaster_Program_team
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Team>("cm_checklistmaster_Program_team", null);
			}
			set
			{
				this.OnPropertyChanging("cm_checklistmaster_Program_team");
				this.SetRelatedEntity<Plugins.Models.Team>("cm_checklistmaster_Program_team", null, value);
				this.OnPropertyChanged("cm_checklistmaster_Program_team");
			}
		}
		
		/// <summary>
		/// N:1 cm_checklistmaster_Survey_msfp_survey
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_survey")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_checklistmaster_Survey_msfp_survey")]
		public Plugins.Models.msfp_survey cm_checklistmaster_Survey_msfp_survey
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.msfp_survey>("cm_checklistmaster_Survey_msfp_survey", null);
			}
			set
			{
				this.OnPropertyChanging("cm_checklistmaster_Survey_msfp_survey");
				this.SetRelatedEntity<Plugins.Models.msfp_survey>("cm_checklistmaster_Survey_msfp_survey", null, value);
				this.OnPropertyChanged("cm_checklistmaster_Survey_msfp_survey");
			}
		}
		
		/// <summary>
		/// N:1 team_cm_checklistmaster
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_cm_checklistmaster")]
		public Plugins.Models.Team team_cm_checklistmaster
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Team>("team_cm_checklistmaster", null);
			}
		}
	}
}
#pragma warning restore CS1591
