#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Models
{
	
	
	/// <summary>
	/// Status of the Case Checklist Catalog
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum cm_casechecklistcatalog_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Case Checklist Catalog
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum cm_casechecklistcatalog_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cm_casechecklistcatalog")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class cm_CaseChecklistCatalog : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the cm_casechecklistcatalog entity
		/// </summary>
		public partial class Fields
		{
			public const string cm_Acitve = "cm_acitve";
			public const string cm_acitveName = "cm_acitvename";
			public const string cm_AnswerType = "cm_answertype";
			public const string cm_answertypeName = "cm_answertypename";
			public const string cm_CaseCategory = "cm_casecategory";
			public const string cm_CaseCategoryName = "cm_casecategoryname";
			public const string cm_CaseChecklistCatalogId = "cm_casechecklistcatalogid";
			public const string Id = "cm_casechecklistcatalogid";
			public const string cm_CaseSubCategory = "cm_casesubcategory";
			public const string cm_CaseSubCategoryName = "cm_casesubcategoryname";
			public const string cm_DisplayOrder = "cm_displayorder";
			public const string cm_IsConditional = "cm_isconditional";
			public const string cm_isconditionalName = "cm_isconditionalname";
			public const string cm_Itemtext = "cm_itemtext";
			public const string cm_Name = "cm_name";
			public const string cm_ParentItem = "cm_parentitem";
			public const string cm_ParentItemName = "cm_parentitemname";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string Referencedcm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog = "Referencedcm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog";
			public const string cm_casechecklistresponse_ItemLink_cm_casechecklistcatalog = "cm_casechecklistresponse_ItemLink_cm_casechecklistcatalog";
			public const string cm_programassociation_CaseChecklistCatalog_cm_casechecklistcatalog = "cm_programassociation_CaseChecklistCatalog_cm_casechecklistcatalog";
			public const string cm_casechecklistcatalog_CaseCategory_cm_casecategory = "cm_casechecklistcatalog_CaseCategory_cm_casecategory";
			public const string cm_casechecklistcatalog_CaseSubCategory_cm_casesubcategory = "cm_casechecklistcatalog_CaseSubCategory_cm_casesubcategory";
			public const string Referencingcm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog = "cm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog";
			public const string team_cm_casechecklistcatalog = "team_cm_casechecklistcatalog";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public cm_CaseChecklistCatalog() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "cm_casechecklistcatalog";
		
		public const string EntityLogicalCollectionName = "cm_casechecklistcatalogs";
		
		public const string EntitySetName = "cm_casechecklistcatalogs";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_acitve")]
		public System.Nullable<bool> cm_Acitve
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cm_acitve");
			}
			set
			{
				this.OnPropertyChanging("cm_Acitve");
				this.SetAttributeValue("cm_acitve", value);
				this.OnPropertyChanged("cm_Acitve");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_acitvename")]
		public string cm_acitveName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_acitve"))
				{
					return this.FormattedValues["cm_acitve"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answertype")]
		public virtual cm_answertype? cm_AnswerType
		{
			get
			{
				return ((cm_answertype?)(EntityOptionSetEnum.GetEnum(this, "cm_answertype")));
			}
			set
			{
				this.OnPropertyChanging("cm_AnswerType");
				this.SetAttributeValue("cm_answertype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("cm_AnswerType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answertypename")]
		public string cm_answertypeName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_answertype"))
				{
					return this.FormattedValues["cm_answertype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casecategory")]
		public Microsoft.Xrm.Sdk.EntityReference cm_CaseCategory
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_casecategory");
			}
			set
			{
				this.OnPropertyChanging("cm_CaseCategory");
				this.SetAttributeValue("cm_casecategory", value);
				this.OnPropertyChanged("cm_CaseCategory");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casecategoryname")]
		public string cm_CaseCategoryName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_casecategory"))
				{
					return this.FormattedValues["cm_casecategory"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casechecklistcatalogid")]
		public System.Nullable<System.Guid> cm_CaseChecklistCatalogId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("cm_casechecklistcatalogid");
			}
			set
			{
				this.OnPropertyChanging("cm_CaseChecklistCatalogId");
				this.SetAttributeValue("cm_casechecklistcatalogid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("cm_CaseChecklistCatalogId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casechecklistcatalogid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.cm_CaseChecklistCatalogId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casesubcategory")]
		public Microsoft.Xrm.Sdk.EntityReference cm_CaseSubCategory
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_casesubcategory");
			}
			set
			{
				this.OnPropertyChanging("cm_CaseSubCategory");
				this.SetAttributeValue("cm_casesubcategory", value);
				this.OnPropertyChanged("cm_CaseSubCategory");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casesubcategoryname")]
		public string cm_CaseSubCategoryName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_casesubcategory"))
				{
					return this.FormattedValues["cm_casesubcategory"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Defines sequence in which questions should be displayed
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_displayorder")]
		public System.Nullable<int> cm_DisplayOrder
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("cm_displayorder");
			}
			set
			{
				this.OnPropertyChanging("cm_DisplayOrder");
				this.SetAttributeValue("cm_displayorder", value);
				this.OnPropertyChanged("cm_DisplayOrder");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_isconditional")]
		public System.Nullable<bool> cm_IsConditional
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cm_isconditional");
			}
			set
			{
				this.OnPropertyChanging("cm_IsConditional");
				this.SetAttributeValue("cm_isconditional", value);
				this.OnPropertyChanged("cm_IsConditional");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_isconditionalname")]
		public string cm_isconditionalName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_isconditional"))
				{
					return this.FormattedValues["cm_isconditional"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_itemtext")]
		public string cm_Itemtext
		{
			get
			{
				return this.GetAttributeValue<string>("cm_itemtext");
			}
			set
			{
				this.OnPropertyChanging("cm_Itemtext");
				this.SetAttributeValue("cm_itemtext", value);
				this.OnPropertyChanged("cm_Itemtext");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_name")]
		public string cm_Name
		{
			get
			{
				return this.GetAttributeValue<string>("cm_name");
			}
			set
			{
				this.OnPropertyChanging("cm_Name");
				this.SetAttributeValue("cm_name", value);
				this.OnPropertyChanged("cm_Name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_parentitem")]
		public Microsoft.Xrm.Sdk.EntityReference cm_ParentItem
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_parentitem");
			}
			set
			{
				this.OnPropertyChanging("cm_ParentItem");
				this.SetAttributeValue("cm_parentitem", value);
				this.OnPropertyChanged("cm_ParentItem");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_parentitemname")]
		public string cm_ParentItemName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_parentitem"))
				{
					return this.FormattedValues["cm_parentitem"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Case Checklist Catalog
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual cm_casechecklistcatalog_statecode? statecode
		{
			get
			{
				return ((cm_casechecklistcatalog_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Case Checklist Catalog
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual cm_casechecklistcatalog_statuscode? statuscode
		{
			get
			{
				return ((cm_casechecklistcatalog_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N cm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<Plugins.Models.cm_CaseChecklistCatalog> Referencedcm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog
		{
			get
			{
				return this.GetRelatedEntities<Plugins.Models.cm_CaseChecklistCatalog>("cm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencedcm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog");
				this.SetRelatedEntities<Plugins.Models.cm_CaseChecklistCatalog>("cm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedcm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog");
			}
		}
		
		/// <summary>
		/// 1:N cm_casechecklistresponse_ItemLink_cm_casechecklistcatalog
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_casechecklistresponse_ItemLink_cm_casechecklistcatalog")]
		public System.Collections.Generic.IEnumerable<Plugins.Models.cm_CaseChecklistResponse> cm_casechecklistresponse_ItemLink_cm_casechecklistcatalog
		{
			get
			{
				return this.GetRelatedEntities<Plugins.Models.cm_CaseChecklistResponse>("cm_casechecklistresponse_ItemLink_cm_casechecklistcatalog", null);
			}
			set
			{
				this.OnPropertyChanging("cm_casechecklistresponse_ItemLink_cm_casechecklistcatalog");
				this.SetRelatedEntities<Plugins.Models.cm_CaseChecklistResponse>("cm_casechecklistresponse_ItemLink_cm_casechecklistcatalog", null, value);
				this.OnPropertyChanged("cm_casechecklistresponse_ItemLink_cm_casechecklistcatalog");
			}
		}
		
		/// <summary>
		/// 1:N cm_programassociation_CaseChecklistCatalog_cm_casechecklistcatalog
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_programassociation_CaseChecklistCatalog_cm_casechecklistcatalog")]
		public System.Collections.Generic.IEnumerable<Plugins.Models.cm_ProgramAssociation> cm_programassociation_CaseChecklistCatalog_cm_casechecklistcatalog
		{
			get
			{
				return this.GetRelatedEntities<Plugins.Models.cm_ProgramAssociation>("cm_programassociation_CaseChecklistCatalog_cm_casechecklistcatalog", null);
			}
			set
			{
				this.OnPropertyChanging("cm_programassociation_CaseChecklistCatalog_cm_casechecklistcatalog");
				this.SetRelatedEntities<Plugins.Models.cm_ProgramAssociation>("cm_programassociation_CaseChecklistCatalog_cm_casechecklistcatalog", null, value);
				this.OnPropertyChanged("cm_programassociation_CaseChecklistCatalog_cm_casechecklistcatalog");
			}
		}
		
		/// <summary>
		/// N:1 cm_casechecklistcatalog_CaseCategory_cm_casecategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casecategory")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_casechecklistcatalog_CaseCategory_cm_casecategory")]
		public Plugins.Models.cm_CaseCategory cm_casechecklistcatalog_CaseCategory_cm_casecategory
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.cm_CaseCategory>("cm_casechecklistcatalog_CaseCategory_cm_casecategory", null);
			}
			set
			{
				this.OnPropertyChanging("cm_casechecklistcatalog_CaseCategory_cm_casecategory");
				this.SetRelatedEntity<Plugins.Models.cm_CaseCategory>("cm_casechecklistcatalog_CaseCategory_cm_casecategory", null, value);
				this.OnPropertyChanged("cm_casechecklistcatalog_CaseCategory_cm_casecategory");
			}
		}
		
		/// <summary>
		/// N:1 cm_casechecklistcatalog_CaseSubCategory_cm_casesubcategory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_casesubcategory")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_casechecklistcatalog_CaseSubCategory_cm_casesubcategory")]
		public Plugins.Models.cm_CaseSubCategory cm_casechecklistcatalog_CaseSubCategory_cm_casesubcategory
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.cm_CaseSubCategory>("cm_casechecklistcatalog_CaseSubCategory_cm_casesubcategory", null);
			}
			set
			{
				this.OnPropertyChanging("cm_casechecklistcatalog_CaseSubCategory_cm_casesubcategory");
				this.SetRelatedEntity<Plugins.Models.cm_CaseSubCategory>("cm_casechecklistcatalog_CaseSubCategory_cm_casesubcategory", null, value);
				this.OnPropertyChanged("cm_casechecklistcatalog_CaseSubCategory_cm_casesubcategory");
			}
		}
		
		/// <summary>
		/// N:1 cm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_parentitem")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public Plugins.Models.cm_CaseChecklistCatalog Referencingcm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.cm_CaseChecklistCatalog>("cm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingcm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog");
				this.SetRelatedEntity<Plugins.Models.cm_CaseChecklistCatalog>("cm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingcm_casechecklistcatalog_ParentItem_cm_casechecklistcatalog");
			}
		}
		
		/// <summary>
		/// N:1 team_cm_casechecklistcatalog
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_cm_casechecklistcatalog")]
		public Plugins.Models.Team team_cm_casechecklistcatalog
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Team>("team_cm_casechecklistcatalog", null);
			}
		}
	}
}
#pragma warning restore CS1591
