#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum cm_leadclosurechecklistresponse_cm_answeryesno
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 121540000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 121540001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum cm_leadclosurechecklistresponse_cm_validateclosureonlyifoppqualificationstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NA = 121540000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QualifiedasVoluntaryProducer = 121540002,
	}
	
	/// <summary>
	/// Status of the Lead Closure Checklist Response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum cm_leadclosurechecklistresponse_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Lead Closure Checklist Response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum cm_leadclosurechecklistresponse_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cm_leadclosurechecklistresponse")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class cm_LeadClosureChecklistResponse : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the cm_leadclosurechecklistresponse entity
		/// </summary>
		public partial class Fields
		{
			public const string cm_Account = "cm_account";
			public const string cm_AccountName = "cm_accountname";
			public const string cm_AccountYomiName = "cm_accountyominame";
			public const string cm_AnswerText = "cm_answertext";
			public const string cm_AnswerType = "cm_answertype";
			public const string cm_answertypeName = "cm_answertypename";
			public const string cm_AnswerYesNo = "cm_answeryesno";
			public const string cm_answeryesnoName = "cm_answeryesnoname";
			public const string cm_ExpectedAnswerToClose = "cm_expectedanswertoclose";
			public const string cm_expectedanswertocloseName = "cm_expectedanswertoclosename";
			public const string cm_LeadClosureChecklistMaster = "cm_leadclosurechecklistmaster";
			public const string cm_LeadClosureChecklistMasterName = "cm_leadclosurechecklistmastername";
			public const string cm_LeadClosureChecklistQuestionLink = "cm_leadclosurechecklistquestionlink";
			public const string cm_LeadClosureChecklistQuestionLinkName = "cm_leadclosurechecklistquestionlinkname";
			public const string cm_LeadClosureChecklistResponseId = "cm_leadclosurechecklistresponseid";
			public const string Id = "cm_leadclosurechecklistresponseid";
			public const string cm_Opportunity = "cm_opportunity";
			public const string cm_OpportunityName = "cm_opportunityname";
			public const string cm_Program = "cm_program";
			public const string cm_ProgramName = "cm_programname";
			public const string cm_ProgramYomiName = "cm_programyominame";
			public const string cm_Question = "cm_question";
			public const string cm_RequiredToClose = "cm_requiredtoclose";
			public const string cm_requiredtocloseName = "cm_requiredtoclosename";
			public const string cm_ResponseDate = "cm_responsedate";
			public const string cm_ResponseID = "cm_responseid";
			public const string cm_ValidateClosureOnlyifOppQualificationStatus = "cm_validateclosureonlyifoppqualificationstatus";
			public const string cm_validateclosureonlyifoppqualificationstatusName = "cm_validateclosureonlyifoppqualificationstatusname";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string cm_leadclosurechecklistresponse_Account_account = "cm_leadclosurechecklistresponse_Account_account";
			public const string cm_leadclosurechecklistresponse_LeadClosureChecklistMaster_cm_leadclosurechecklistmaster = "cm_leadclosurechecklistresponse_LeadClosureChecklistMaster_cm_leadclosurechecklis" +
		"tmaster";
			public const string cm_leadclosurechecklistresponse_LeadClosureChecklistQuestionLink_cm_leadclosurechecklistcatalog = "cm_leadclosurechecklistresponse_LeadClosureChecklistQuestionLink_cm_leadclosurech" +
		"ecklistcatalog";
			public const string cm_leadclosurechecklistresponse_Opportunity_opportunity = "cm_leadclosurechecklistresponse_Opportunity_opportunity";
			public const string cm_leadclosurechecklistresponse_Program_team = "cm_leadclosurechecklistresponse_Program_team";
			public const string lk_cm_leadclosurechecklistresponse_createdby = "lk_cm_leadclosurechecklistresponse_createdby";
			public const string lk_cm_leadclosurechecklistresponse_createdonbehalfby = "lk_cm_leadclosurechecklistresponse_createdonbehalfby";
			public const string lk_cm_leadclosurechecklistresponse_modifiedby = "lk_cm_leadclosurechecklistresponse_modifiedby";
			public const string lk_cm_leadclosurechecklistresponse_modifiedonbehalfby = "lk_cm_leadclosurechecklistresponse_modifiedonbehalfby";
			public const string team_cm_leadclosurechecklistresponse = "team_cm_leadclosurechecklistresponse";
			public const string user_cm_leadclosurechecklistresponse = "user_cm_leadclosurechecklistresponse";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public cm_LeadClosureChecklistResponse() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "cm_leadclosurechecklistresponse";
		
		public const string EntityLogicalCollectionName = "cm_leadclosurechecklistresponses";
		
		public const string EntitySetName = "cm_leadclosurechecklistresponses";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Account to which the Lead Closure Checklist responses are related to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_account")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Account
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_account");
			}
			set
			{
				this.OnPropertyChanging("cm_Account");
				this.SetAttributeValue("cm_account", value);
				this.OnPropertyChanged("cm_Account");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_accountname")]
		public string cm_AccountName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_account"))
				{
					return this.FormattedValues["cm_account"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_accountyominame")]
		public string cm_AccountYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_account"))
				{
					return this.FormattedValues["cm_account"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Answer Text field if the question answer type is Text.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answertext")]
		public string cm_AnswerText
		{
			get
			{
				return this.GetAttributeValue<string>("cm_answertext");
			}
			set
			{
				this.OnPropertyChanging("cm_AnswerText");
				this.SetAttributeValue("cm_answertext", value);
				this.OnPropertyChanged("cm_AnswerText");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answertype")]
		public virtual cm_answertype? cm_AnswerType
		{
			get
			{
				return ((cm_answertype?)(EntityOptionSetEnum.GetEnum(this, "cm_answertype")));
			}
			set
			{
				this.OnPropertyChanging("cm_AnswerType");
				this.SetAttributeValue("cm_answertype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("cm_AnswerType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answertypename")]
		public string cm_answertypeName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_answertype"))
				{
					return this.FormattedValues["cm_answertype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Answer Yes/No field if the question answer type is Yes/No.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answeryesno")]
		public virtual cm_leadclosurechecklistresponse_cm_answeryesno? cm_AnswerYesNo
		{
			get
			{
				return ((cm_leadclosurechecklistresponse_cm_answeryesno?)(EntityOptionSetEnum.GetEnum(this, "cm_answeryesno")));
			}
			set
			{
				this.OnPropertyChanging("cm_AnswerYesNo");
				this.SetAttributeValue("cm_answeryesno", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("cm_AnswerYesNo");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answeryesnoname")]
		public string cm_answeryesnoName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_answeryesno"))
				{
					return this.FormattedValues["cm_answeryesno"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_expectedanswertoclose")]
		public virtual cm_expectedanswertoclose? cm_ExpectedAnswerToClose
		{
			get
			{
				return ((cm_expectedanswertoclose?)(EntityOptionSetEnum.GetEnum(this, "cm_expectedanswertoclose")));
			}
			set
			{
				this.OnPropertyChanging("cm_ExpectedAnswerToClose");
				this.SetAttributeValue("cm_expectedanswertoclose", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("cm_ExpectedAnswerToClose");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_expectedanswertoclosename")]
		public string cm_expectedanswertocloseName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_expectedanswertoclose"))
				{
					return this.FormattedValues["cm_expectedanswertoclose"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Lookup to the Lead Closure Checklist Master table.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_leadclosurechecklistmaster")]
		public Microsoft.Xrm.Sdk.EntityReference cm_LeadClosureChecklistMaster
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_leadclosurechecklistmaster");
			}
			set
			{
				this.OnPropertyChanging("cm_LeadClosureChecklistMaster");
				this.SetAttributeValue("cm_leadclosurechecklistmaster", value);
				this.OnPropertyChanged("cm_LeadClosureChecklistMaster");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_leadclosurechecklistmastername")]
		public string cm_LeadClosureChecklistMasterName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_leadclosurechecklistmaster"))
				{
					return this.FormattedValues["cm_leadclosurechecklistmaster"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Lookup to the Lead Closure Checklist Catalog table to identify which question this response is for.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_leadclosurechecklistquestionlink")]
		public Microsoft.Xrm.Sdk.EntityReference cm_LeadClosureChecklistQuestionLink
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_leadclosurechecklistquestionlink");
			}
			set
			{
				this.OnPropertyChanging("cm_LeadClosureChecklistQuestionLink");
				this.SetAttributeValue("cm_leadclosurechecklistquestionlink", value);
				this.OnPropertyChanged("cm_LeadClosureChecklistQuestionLink");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_leadclosurechecklistquestionlinkname")]
		public string cm_LeadClosureChecklistQuestionLinkName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_leadclosurechecklistquestionlink"))
				{
					return this.FormattedValues["cm_leadclosurechecklistquestionlink"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_leadclosurechecklistresponseid")]
		public System.Nullable<System.Guid> cm_LeadClosureChecklistResponseId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("cm_leadclosurechecklistresponseid");
			}
			set
			{
				this.OnPropertyChanging("cm_LeadClosureChecklistResponseId");
				this.SetAttributeValue("cm_leadclosurechecklistresponseid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("cm_LeadClosureChecklistResponseId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_leadclosurechecklistresponseid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.cm_LeadClosureChecklistResponseId = value;
			}
		}
		
		/// <summary>
		/// The opportunity the closure checklist responses are linked to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_opportunity")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Opportunity
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_opportunity");
			}
			set
			{
				this.OnPropertyChanging("cm_Opportunity");
				this.SetAttributeValue("cm_opportunity", value);
				this.OnPropertyChanged("cm_Opportunity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_opportunityname")]
		public string cm_OpportunityName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_opportunity"))
				{
					return this.FormattedValues["cm_opportunity"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Program related to the question, inherited from the Lead Closure Checklist Master.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_program")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Program
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_program");
			}
			set
			{
				this.OnPropertyChanging("cm_Program");
				this.SetAttributeValue("cm_program", value);
				this.OnPropertyChanged("cm_Program");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_programname")]
		public string cm_ProgramName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_program"))
				{
					return this.FormattedValues["cm_program"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_programyominame")]
		public string cm_ProgramYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_program"))
				{
					return this.FormattedValues["cm_program"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_question")]
		public string cm_Question
		{
			get
			{
				return this.GetAttributeValue<string>("cm_question");
			}
			set
			{
				this.OnPropertyChanging("cm_Question");
				this.SetAttributeValue("cm_question", value);
				this.OnPropertyChanged("cm_Question");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_requiredtoclose")]
		public System.Nullable<bool> cm_RequiredToClose
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cm_requiredtoclose");
			}
			set
			{
				this.OnPropertyChanging("cm_RequiredToClose");
				this.SetAttributeValue("cm_requiredtoclose", value);
				this.OnPropertyChanged("cm_RequiredToClose");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_requiredtoclosename")]
		public string cm_requiredtocloseName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_requiredtoclose"))
				{
					return this.FormattedValues["cm_requiredtoclose"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Timestamp of when the response was recorded.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_responsedate")]
		public System.Nullable<System.DateTime> cm_ResponseDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("cm_responsedate");
			}
			set
			{
				this.OnPropertyChanging("cm_ResponseDate");
				this.SetAttributeValue("cm_responsedate", value);
				this.OnPropertyChanged("cm_ResponseDate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_responseid")]
		public string cm_ResponseID
		{
			get
			{
				return this.GetAttributeValue<string>("cm_responseid");
			}
			set
			{
				this.OnPropertyChanging("cm_ResponseID");
				this.SetAttributeValue("cm_responseid", value);
				this.OnPropertyChanged("cm_ResponseID");
			}
		}
		
		/// <summary>
		/// Maintain this field value as per the Lead Closure Checklist Catalog
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_validateclosureonlyifoppqualificationstatus")]
		public virtual cm_leadclosurechecklistresponse_cm_validateclosureonlyifoppqualificationstatus? cm_ValidateClosureOnlyifOppQualificationStatus
		{
			get
			{
				return ((cm_leadclosurechecklistresponse_cm_validateclosureonlyifoppqualificationstatus?)(EntityOptionSetEnum.GetEnum(this, "cm_validateclosureonlyifoppqualificationstatus")));
			}
			set
			{
				this.OnPropertyChanging("cm_ValidateClosureOnlyifOppQualificationStatus");
				this.SetAttributeValue("cm_validateclosureonlyifoppqualificationstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("cm_ValidateClosureOnlyifOppQualificationStatus");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_validateclosureonlyifoppqualificationstatusname")]
		public string cm_validateclosureonlyifoppqualificationstatusName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_validateclosureonlyifoppqualificationstatus"))
				{
					return this.FormattedValues["cm_validateclosureonlyifoppqualificationstatus"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Lead Closure Checklist Response
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual cm_leadclosurechecklistresponse_statecode? statecode
		{
			get
			{
				return ((cm_leadclosurechecklistresponse_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Lead Closure Checklist Response
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual cm_leadclosurechecklistresponse_statuscode? statuscode
		{
			get
			{
				return ((cm_leadclosurechecklistresponse_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 cm_leadclosurechecklistresponse_Account_account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_account")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_leadclosurechecklistresponse_Account_account")]
		public Plugins.Models.Account cm_leadclosurechecklistresponse_Account_account
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Account>("cm_leadclosurechecklistresponse_Account_account", null);
			}
			set
			{
				this.OnPropertyChanging("cm_leadclosurechecklistresponse_Account_account");
				this.SetRelatedEntity<Plugins.Models.Account>("cm_leadclosurechecklistresponse_Account_account", null, value);
				this.OnPropertyChanged("cm_leadclosurechecklistresponse_Account_account");
			}
		}
		
		/// <summary>
		/// N:1 cm_leadclosurechecklistresponse_LeadClosureChecklistMaster_cm_leadclosurechecklistmaster
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_leadclosurechecklistmaster")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_leadclosurechecklistresponse_LeadClosureChecklistMaster_cm_leadclosurechecklis" +
			"tmaster")]
		public Plugins.Models.cm_LeadClosureChecklistMaster cm_leadclosurechecklistresponse_LeadClosureChecklistMaster_cm_leadclosurechecklistmaster
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.cm_LeadClosureChecklistMaster>("cm_leadclosurechecklistresponse_LeadClosureChecklistMaster_cm_leadclosurechecklis" +
						"tmaster", null);
			}
			set
			{
				this.OnPropertyChanging("cm_leadclosurechecklistresponse_LeadClosureChecklistMaster_cm_leadclosurechecklis" +
						"tmaster");
				this.SetRelatedEntity<Plugins.Models.cm_LeadClosureChecklistMaster>("cm_leadclosurechecklistresponse_LeadClosureChecklistMaster_cm_leadclosurechecklis" +
						"tmaster", null, value);
				this.OnPropertyChanged("cm_leadclosurechecklistresponse_LeadClosureChecklistMaster_cm_leadclosurechecklis" +
						"tmaster");
			}
		}
		
		/// <summary>
		/// N:1 cm_leadclosurechecklistresponse_LeadClosureChecklistQuestionLink_cm_leadclosurechecklistcatalog
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_leadclosurechecklistquestionlink")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_leadclosurechecklistresponse_LeadClosureChecklistQuestionLink_cm_leadclosurech" +
			"ecklistcatalog")]
		public Plugins.Models.cm_LeadClosureChecklistCatalog cm_leadclosurechecklistresponse_LeadClosureChecklistQuestionLink_cm_leadclosurechecklistcatalog
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.cm_LeadClosureChecklistCatalog>("cm_leadclosurechecklistresponse_LeadClosureChecklistQuestionLink_cm_leadclosurech" +
						"ecklistcatalog", null);
			}
			set
			{
				this.OnPropertyChanging("cm_leadclosurechecklistresponse_LeadClosureChecklistQuestionLink_cm_leadclosurech" +
						"ecklistcatalog");
				this.SetRelatedEntity<Plugins.Models.cm_LeadClosureChecklistCatalog>("cm_leadclosurechecklistresponse_LeadClosureChecklistQuestionLink_cm_leadclosurech" +
						"ecklistcatalog", null, value);
				this.OnPropertyChanged("cm_leadclosurechecklistresponse_LeadClosureChecklistQuestionLink_cm_leadclosurech" +
						"ecklistcatalog");
			}
		}
		
		/// <summary>
		/// N:1 cm_leadclosurechecklistresponse_Opportunity_opportunity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_opportunity")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_leadclosurechecklistresponse_Opportunity_opportunity")]
		public Plugins.Models.Opportunity cm_leadclosurechecklistresponse_Opportunity_opportunity
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Opportunity>("cm_leadclosurechecklistresponse_Opportunity_opportunity", null);
			}
			set
			{
				this.OnPropertyChanging("cm_leadclosurechecklistresponse_Opportunity_opportunity");
				this.SetRelatedEntity<Plugins.Models.Opportunity>("cm_leadclosurechecklistresponse_Opportunity_opportunity", null, value);
				this.OnPropertyChanged("cm_leadclosurechecklistresponse_Opportunity_opportunity");
			}
		}
		
		/// <summary>
		/// N:1 cm_leadclosurechecklistresponse_Program_team
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_program")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_leadclosurechecklistresponse_Program_team")]
		public Plugins.Models.Team cm_leadclosurechecklistresponse_Program_team
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Team>("cm_leadclosurechecklistresponse_Program_team", null);
			}
			set
			{
				this.OnPropertyChanging("cm_leadclosurechecklistresponse_Program_team");
				this.SetRelatedEntity<Plugins.Models.Team>("cm_leadclosurechecklistresponse_Program_team", null, value);
				this.OnPropertyChanged("cm_leadclosurechecklistresponse_Program_team");
			}
		}
		
		/// <summary>
		/// N:1 lk_cm_leadclosurechecklistresponse_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_cm_leadclosurechecklistresponse_createdby")]
		public Plugins.Models.SystemUser lk_cm_leadclosurechecklistresponse_createdby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_cm_leadclosurechecklistresponse_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_cm_leadclosurechecklistresponse_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_cm_leadclosurechecklistresponse_createdonbehalfby")]
		public Plugins.Models.SystemUser lk_cm_leadclosurechecklistresponse_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_cm_leadclosurechecklistresponse_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_cm_leadclosurechecklistresponse_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_cm_leadclosurechecklistresponse_modifiedby")]
		public Plugins.Models.SystemUser lk_cm_leadclosurechecklistresponse_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_cm_leadclosurechecklistresponse_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_cm_leadclosurechecklistresponse_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_cm_leadclosurechecklistresponse_modifiedonbehalfby")]
		public Plugins.Models.SystemUser lk_cm_leadclosurechecklistresponse_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_cm_leadclosurechecklistresponse_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 team_cm_leadclosurechecklistresponse
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_cm_leadclosurechecklistresponse")]
		public Plugins.Models.Team team_cm_leadclosurechecklistresponse
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Team>("team_cm_leadclosurechecklistresponse", null);
			}
		}
		
		/// <summary>
		/// N:1 user_cm_leadclosurechecklistresponse
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_cm_leadclosurechecklistresponse")]
		public Plugins.Models.SystemUser user_cm_leadclosurechecklistresponse
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("user_cm_leadclosurechecklistresponse", null);
			}
		}
	}
}
#pragma warning restore CS1591
