#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum cm_questionresponse_cm_answeryesno
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 121540000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 121540001,
	}
	
	/// <summary>
	/// Status of the Question Response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum cm_questionresponse_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Question Response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum cm_questionresponse_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cm_questionresponse")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public partial class cm_QuestionResponse : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the cm_questionresponse entity
		/// </summary>
		public partial class Fields
		{
			public const string cm_Account = "cm_account";
			public const string cm_AccountName = "cm_accountname";
			public const string cm_AccountYomiName = "cm_accountyominame";
			public const string cm_AnswerText = "cm_answertext";
			public const string cm_AnswerType = "cm_answertype";
			public const string cm_answertypeName = "cm_answertypename";
			public const string cm_AnswerYesNo = "cm_answeryesno";
			public const string cm_answeryesnoName = "cm_answeryesnoname";
			public const string cm_Opportunity = "cm_opportunity";
			public const string cm_OpportunityName = "cm_opportunityname";
			public const string cm_Program = "cm_program";
			public const string cm_ProgramName = "cm_programname";
			public const string cm_ProgramYomiName = "cm_programyominame";
			public const string cm_Province = "cm_province";
			public const string cm_ProvinceName = "cm_provincename";
			public const string cm_Question = "cm_question";
			public const string cm_QuestionName = "cm_questionname";
			public const string cm_QuestionResponseId = "cm_questionresponseid";
			public const string Id = "cm_questionresponseid";
			public const string cm_QuestionText = "cm_questiontext";
			public const string cm_ResponseDate = "cm_responsedate";
			public const string cm_ResponseID = "cm_responseid";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string cm_questionresponse_Account_account = "cm_questionresponse_Account_account";
			public const string cm_questionresponse_Opportunity_opportunity = "cm_questionresponse_Opportunity_opportunity";
			public const string cm_questionresponse_Program_team = "cm_questionresponse_Program_team";
			public const string cm_questionresponse_Province_cm_province = "cm_questionresponse_Province_cm_province";
			public const string cm_questionresponse_Question_cm_questioncatalog = "cm_questionresponse_Question_cm_questioncatalog";
			public const string team_cm_questionresponse = "team_cm_questionresponse";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public cm_QuestionResponse() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "cm_questionresponse";
		
		public const string EntityLogicalCollectionName = "cm_questionresponses";
		
		public const string EntitySetName = "cm_questionresponses";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_account")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Account
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_account");
			}
			set
			{
				this.OnPropertyChanging("cm_Account");
				this.SetAttributeValue("cm_account", value);
				this.OnPropertyChanged("cm_Account");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_accountname")]
		public string cm_AccountName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_account"))
				{
					return this.FormattedValues["cm_account"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_accountyominame")]
		public string cm_AccountYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_account"))
				{
					return this.FormattedValues["cm_account"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Answer Text field if the question answer type is Text.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answertext")]
		public string cm_AnswerText
		{
			get
			{
				return this.GetAttributeValue<string>("cm_answertext");
			}
			set
			{
				this.OnPropertyChanging("cm_AnswerText");
				this.SetAttributeValue("cm_answertext", value);
				this.OnPropertyChanged("cm_AnswerText");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answertype")]
		public virtual cm_answertype? cm_AnswerType
		{
			get
			{
				return ((cm_answertype?)(EntityOptionSetEnum.GetEnum(this, "cm_answertype")));
			}
			set
			{
				this.OnPropertyChanging("cm_AnswerType");
				this.SetAttributeValue("cm_answertype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("cm_AnswerType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answertypename")]
		public string cm_answertypeName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_answertype"))
				{
					return this.FormattedValues["cm_answertype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Answer Yes/No field if the question answer type is Yes/No.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answeryesno")]
		public virtual cm_questionresponse_cm_answeryesno? cm_AnswerYesNo
		{
			get
			{
				return ((cm_questionresponse_cm_answeryesno?)(EntityOptionSetEnum.GetEnum(this, "cm_answeryesno")));
			}
			set
			{
				this.OnPropertyChanging("cm_AnswerYesNo");
				this.SetAttributeValue("cm_answeryesno", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("cm_AnswerYesNo");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_answeryesnoname")]
		public string cm_answeryesnoName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_answeryesno"))
				{
					return this.FormattedValues["cm_answeryesno"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The opportunity the responses are linked to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_opportunity")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Opportunity
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_opportunity");
			}
			set
			{
				this.OnPropertyChanging("cm_Opportunity");
				this.SetAttributeValue("cm_opportunity", value);
				this.OnPropertyChanged("cm_Opportunity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_opportunityname")]
		public string cm_OpportunityName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_opportunity"))
				{
					return this.FormattedValues["cm_opportunity"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Program related to the question, inherited from the Question Master.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_program")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Program
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_program");
			}
			set
			{
				this.OnPropertyChanging("cm_Program");
				this.SetAttributeValue("cm_program", value);
				this.OnPropertyChanged("cm_Program");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_programname")]
		public string cm_ProgramName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_program"))
				{
					return this.FormattedValues["cm_program"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_programyominame")]
		public string cm_ProgramYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_program"))
				{
					return this.FormattedValues["cm_program"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Province related to the question, inherited from the Question Master.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_province")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Province
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_province");
			}
			set
			{
				this.OnPropertyChanging("cm_Province");
				this.SetAttributeValue("cm_province", value);
				this.OnPropertyChanged("cm_Province");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_provincename")]
		public string cm_ProvinceName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_province"))
				{
					return this.FormattedValues["cm_province"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Lookup to the Question Master table to identify which question this response is for.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_question")]
		public Microsoft.Xrm.Sdk.EntityReference cm_Question
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cm_question");
			}
			set
			{
				this.OnPropertyChanging("cm_Question");
				this.SetAttributeValue("cm_question", value);
				this.OnPropertyChanged("cm_Question");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_questionname")]
		public string cm_QuestionName
		{
			get
			{
				if (this.FormattedValues.Contains("cm_question"))
				{
					return this.FormattedValues["cm_question"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_questionresponseid")]
		public System.Nullable<System.Guid> cm_QuestionResponseId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("cm_questionresponseid");
			}
			set
			{
				this.OnPropertyChanging("cm_QuestionResponseId");
				this.SetAttributeValue("cm_questionresponseid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("cm_QuestionResponseId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_questionresponseid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.cm_QuestionResponseId = value;
			}
		}
		
		/// <summary>
		/// Question Text
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_questiontext")]
		public string cm_QuestionText
		{
			get
			{
				return this.GetAttributeValue<string>("cm_questiontext");
			}
			set
			{
				this.OnPropertyChanging("cm_QuestionText");
				this.SetAttributeValue("cm_questiontext", value);
				this.OnPropertyChanged("cm_QuestionText");
			}
		}
		
		/// <summary>
		/// Timestamp of when the response was recorded.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_responsedate")]
		public System.Nullable<System.DateTime> cm_ResponseDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("cm_responsedate");
			}
			set
			{
				this.OnPropertyChanging("cm_ResponseDate");
				this.SetAttributeValue("cm_responsedate", value);
				this.OnPropertyChanged("cm_ResponseDate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_responseid")]
		public string cm_ResponseID
		{
			get
			{
				return this.GetAttributeValue<string>("cm_responseid");
			}
			set
			{
				this.OnPropertyChanging("cm_ResponseID");
				this.SetAttributeValue("cm_responseid", value);
				this.OnPropertyChanged("cm_ResponseID");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Question Response
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual cm_questionresponse_statecode? statecode
		{
			get
			{
				return ((cm_questionresponse_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Question Response
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual cm_questionresponse_statuscode? statuscode
		{
			get
			{
				return ((cm_questionresponse_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 cm_questionresponse_Account_account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_account")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_questionresponse_Account_account")]
		public Plugins.Models.Account cm_questionresponse_Account_account
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Account>("cm_questionresponse_Account_account", null);
			}
			set
			{
				this.OnPropertyChanging("cm_questionresponse_Account_account");
				this.SetRelatedEntity<Plugins.Models.Account>("cm_questionresponse_Account_account", null, value);
				this.OnPropertyChanged("cm_questionresponse_Account_account");
			}
		}
		
		/// <summary>
		/// N:1 cm_questionresponse_Opportunity_opportunity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_opportunity")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_questionresponse_Opportunity_opportunity")]
		public Plugins.Models.Opportunity cm_questionresponse_Opportunity_opportunity
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Opportunity>("cm_questionresponse_Opportunity_opportunity", null);
			}
			set
			{
				this.OnPropertyChanging("cm_questionresponse_Opportunity_opportunity");
				this.SetRelatedEntity<Plugins.Models.Opportunity>("cm_questionresponse_Opportunity_opportunity", null, value);
				this.OnPropertyChanged("cm_questionresponse_Opportunity_opportunity");
			}
		}
		
		/// <summary>
		/// N:1 cm_questionresponse_Program_team
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_program")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_questionresponse_Program_team")]
		public Plugins.Models.Team cm_questionresponse_Program_team
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Team>("cm_questionresponse_Program_team", null);
			}
			set
			{
				this.OnPropertyChanging("cm_questionresponse_Program_team");
				this.SetRelatedEntity<Plugins.Models.Team>("cm_questionresponse_Program_team", null, value);
				this.OnPropertyChanged("cm_questionresponse_Program_team");
			}
		}
		
		/// <summary>
		/// N:1 cm_questionresponse_Province_cm_province
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_province")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_questionresponse_Province_cm_province")]
		public Plugins.Models.cm_Province cm_questionresponse_Province_cm_province
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.cm_Province>("cm_questionresponse_Province_cm_province", null);
			}
			set
			{
				this.OnPropertyChanging("cm_questionresponse_Province_cm_province");
				this.SetRelatedEntity<Plugins.Models.cm_Province>("cm_questionresponse_Province_cm_province", null, value);
				this.OnPropertyChanged("cm_questionresponse_Province_cm_province");
			}
		}
		
		/// <summary>
		/// N:1 cm_questionresponse_Question_cm_questioncatalog
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cm_question")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_questionresponse_Question_cm_questioncatalog")]
		public Plugins.Models.cm_QuestionCatalog cm_questionresponse_Question_cm_questioncatalog
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.cm_QuestionCatalog>("cm_questionresponse_Question_cm_questioncatalog", null);
			}
			set
			{
				this.OnPropertyChanging("cm_questionresponse_Question_cm_questioncatalog");
				this.SetRelatedEntity<Plugins.Models.cm_QuestionCatalog>("cm_questionresponse_Question_cm_questioncatalog", null, value);
				this.OnPropertyChanged("cm_questionresponse_Question_cm_questioncatalog");
			}
		}
		
		/// <summary>
		/// N:1 team_cm_questionresponse
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_cm_questionresponse")]
		public Plugins.Models.Team team_cm_questionresponse
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Team>("team_cm_questionresponse", null);
			}
		}
	}
}
#pragma warning restore CS1591
