#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Models
{
	
	
	/// <summary>
	/// The secret store where the secret is persisted.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum environmentvariabledefinition_secretstore
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AzureKeyVault = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDataverse = 1,
	}
	
	/// <summary>
	/// Status of the Environment Variable Definition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum environmentvariabledefinition_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Environment Variable Definition
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum environmentvariabledefinition_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum environmentvariabledefinition_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		String = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Boolean = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JSON = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataSource = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Secret = 100000005,
	}
	
	/// <summary>
	/// Contains information about the settable variable: its type, default value, and etc.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("environmentvariabledefinition")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class EnvironmentVariableDefinition : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the environmentvariabledefinition entity
		/// </summary>
		public partial class Fields
		{
			public const string ApiId = "apiid";
			public const string ComponentState = "componentstate";
			public const string componentstateName = "componentstatename";
			public const string ConnectionReferenceId = "connectionreferenceid";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string DefaultValue = "defaultvalue";
			public const string Description = "description";
			public const string DisplayName = "displayname";
			public const string EnvironmentVariableDefinitionId = "environmentvariabledefinitionid";
			public const string Id = "environmentvariabledefinitionid";
			public const string EnvironmentVariableDefinitionIdUnique = "environmentvariabledefinitionidunique";
			public const string Hint = "hint";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string InputControlConfig = "inputcontrolconfig";
			public const string IntroducedVersion = "introducedversion";
			public const string IsCustomizable = "iscustomizable";
			public const string IsManaged = "ismanaged";
			public const string ismanagedName = "ismanagedname";
			public const string IsRequired = "isrequired";
			public const string isrequiredName = "isrequiredname";
			public const string LearnMoreUrl = "learnmoreurl";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OverwriteTime = "overwritetime";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ParameterKey = "parameterkey";
			public const string ParentDefinitionId = "parentdefinitionid";
			public const string ParentDefinitionIdName = "parentdefinitionidname";
			public const string SchemaName = "schemaname";
			public const string SecretStore = "secretstore";
			public const string secretstoreName = "secretstorename";
			public const string SolutionId = "solutionid";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string Type = "type";
			public const string typeName = "typename";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string ValueSchema = "valueschema";
			public const string VersionNumber = "versionnumber";
			public const string Referencedenvdefinition_envdefinition = "Referencedenvdefinition_envdefinition";
			public const string environmentvariabledefinition_environmentvariablevalue = "environmentvariabledefinition_environmentvariablevalue";
			public const string Referencingenvdefinition_envdefinition = "envdefinition_envdefinition";
			public const string lk_environmentvariabledefinition_createdby = "lk_environmentvariabledefinition_createdby";
			public const string lk_environmentvariabledefinition_createdonbehalfby = "lk_environmentvariabledefinition_createdonbehalfby";
			public const string lk_environmentvariabledefinition_modifiedby = "lk_environmentvariabledefinition_modifiedby";
			public const string lk_environmentvariabledefinition_modifiedonbehalfby = "lk_environmentvariabledefinition_modifiedonbehalfby";
			public const string team_environmentvariabledefinition = "team_environmentvariabledefinition";
			public const string user_environmentvariabledefinition = "user_environmentvariabledefinition";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public EnvironmentVariableDefinition() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "environmentvariabledefinition";
		
		public const string EntityLogicalCollectionName = "environmentvariabledefinitions";
		
		public const string EntitySetName = "environmentvariabledefinitions";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apiid")]
		public string ApiId
		{
			get
			{
				return this.GetAttributeValue<string>("apiid");
			}
			set
			{
				this.OnPropertyChanging("ApiId");
				this.SetAttributeValue("apiid", value);
				this.OnPropertyChanged("ApiId");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstatename")]
		public string componentstateName
		{
			get
			{
				if (this.FormattedValues.Contains("componentstate"))
				{
					return this.FormattedValues["componentstate"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Connection Reference associated with Environment Variable Definition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionreferenceid")]
		public Microsoft.Xrm.Sdk.EntityReference ConnectionReferenceId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("connectionreferenceid");
			}
			set
			{
				this.OnPropertyChanging("ConnectionReferenceId");
				this.SetAttributeValue("connectionreferenceid", value);
				this.OnPropertyChanged("ConnectionReferenceId");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Default variable value to be used if no associated EnvironmentVariableValue entities exist.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultvalue")]
		public string DefaultValue
		{
			get
			{
				return this.GetAttributeValue<string>("defaultvalue");
			}
			set
			{
				this.OnPropertyChanging("DefaultValue");
				this.SetAttributeValue("defaultvalue", value);
				this.OnPropertyChanged("DefaultValue");
			}
		}
		
		/// <summary>
		/// Description of the variable definition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// Display Name of the variable definition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("displayname")]
		public string DisplayName
		{
			get
			{
				return this.GetAttributeValue<string>("displayname");
			}
			set
			{
				this.OnPropertyChanging("DisplayName");
				this.SetAttributeValue("displayname", value);
				this.OnPropertyChanged("DisplayName");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("environmentvariabledefinitionid")]
		public System.Nullable<System.Guid> EnvironmentVariableDefinitionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("environmentvariabledefinitionid");
			}
			set
			{
				this.OnPropertyChanging("EnvironmentVariableDefinitionId");
				this.SetAttributeValue("environmentvariabledefinitionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("EnvironmentVariableDefinitionId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("environmentvariabledefinitionid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.EnvironmentVariableDefinitionId = value;
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("environmentvariabledefinitionidunique")]
		public System.Nullable<System.Guid> EnvironmentVariableDefinitionIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("environmentvariabledefinitionidunique");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("hint")]
		public string Hint
		{
			get
			{
				return this.GetAttributeValue<string>("hint");
			}
			set
			{
				this.OnPropertyChanging("Hint");
				this.SetAttributeValue("hint", value);
				this.OnPropertyChanged("Hint");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// A JSON object describing the options for the input control that should be presented to the user for setting the current value of the Environment variable.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("inputcontrolconfig")]
		public string InputControlConfig
		{
			get
			{
				return this.GetAttributeValue<string>("inputcontrolconfig");
			}
			set
			{
				this.OnPropertyChanging("InputControlConfig");
				this.SetAttributeValue("inputcontrolconfig", value);
				this.OnPropertyChanged("InputControlConfig");
			}
		}
		
		/// <summary>
		/// Version in which the form is introduced.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("introducedversion")]
		public string IntroducedVersion
		{
			get
			{
				return this.GetAttributeValue<string>("introducedversion");
			}
			set
			{
				this.OnPropertyChanging("IntroducedVersion");
				this.SetAttributeValue("introducedversion", value);
				this.OnPropertyChanged("IntroducedVersion");
			}
		}
		
		/// <summary>
		/// Tells whether the component can be customized.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.OnPropertyChanging("IsCustomizable");
				this.SetAttributeValue("iscustomizable", value);
				this.OnPropertyChanged("IsCustomizable");
			}
		}
		
		/// <summary>
		/// Indicates whether the solution component is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanagedname")]
		public string ismanagedName
		{
			get
			{
				if (this.FormattedValues.Contains("ismanaged"))
				{
					return this.FormattedValues["ismanaged"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isrequired")]
		public System.Nullable<bool> IsRequired
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isrequired");
			}
			set
			{
				this.OnPropertyChanging("IsRequired");
				this.SetAttributeValue("isrequired", value);
				this.OnPropertyChanged("IsRequired");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isrequiredname")]
		public string isrequiredName
		{
			get
			{
				if (this.FormattedValues.Contains("isrequired"))
				{
					return this.FormattedValues["isrequired"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Clicking on this url will take the user to a webpage which further explains the environment variable being populated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("learnmoreurl")]
		public string LearnMoreUrl
		{
			get
			{
				return this.GetAttributeValue<string>("learnmoreurl");
			}
			set
			{
				this.OnPropertyChanging("LearnMoreUrl");
				this.SetAttributeValue("learnmoreurl", value);
				this.OnPropertyChanged("LearnMoreUrl");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parameterkey")]
		public string ParameterKey
		{
			get
			{
				return this.GetAttributeValue<string>("parameterkey");
			}
			set
			{
				this.OnPropertyChanging("ParameterKey");
				this.SetAttributeValue("parameterkey", value);
				this.OnPropertyChanged("ParameterKey");
			}
		}
		
		/// <summary>
		/// Unique identifier for Environment Variable Definition associated with Environment Variable Definition.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentdefinitionid")]
		public Microsoft.Xrm.Sdk.EntityReference ParentDefinitionId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentdefinitionid");
			}
			set
			{
				this.OnPropertyChanging("ParentDefinitionId");
				this.SetAttributeValue("parentdefinitionid", value);
				this.OnPropertyChanged("ParentDefinitionId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentdefinitionidname")]
		public string ParentDefinitionIdName
		{
			get
			{
				if (this.FormattedValues.Contains("parentdefinitionid"))
				{
					return this.FormattedValues["parentdefinitionid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique entity name.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("schemaname")]
		public string SchemaName
		{
			get
			{
				return this.GetAttributeValue<string>("schemaname");
			}
			set
			{
				this.OnPropertyChanging("SchemaName");
				this.SetAttributeValue("schemaname", value);
				this.OnPropertyChanged("SchemaName");
			}
		}
		
		/// <summary>
		/// Environment variable secret store.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("secretstore")]
		public virtual environmentvariabledefinition_secretstore? SecretStore
		{
			get
			{
				return ((environmentvariabledefinition_secretstore?)(EntityOptionSetEnum.GetEnum(this, "secretstore")));
			}
			set
			{
				this.OnPropertyChanging("SecretStore");
				this.SetAttributeValue("secretstore", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("SecretStore");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("secretstorename")]
		public string secretstoreName
		{
			get
			{
				if (this.FormattedValues.Contains("secretstore"))
				{
					return this.FormattedValues["secretstore"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Status of the Environment Variable Definition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual environmentvariabledefinition_statecode? statecode
		{
			get
			{
				return ((environmentvariabledefinition_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Environment Variable Definition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual environmentvariabledefinition_statuscode? statuscode
		{
			get
			{
				return ((environmentvariabledefinition_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Environment variable value type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("type")]
		public virtual environmentvariabledefinition_type? Type
		{
			get
			{
				return ((environmentvariabledefinition_type?)(EntityOptionSetEnum.GetEnum(this, "type")));
			}
			set
			{
				this.OnPropertyChanging("Type");
				this.SetAttributeValue("type", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("Type");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("typename")]
		public string typeName
		{
			get
			{
				if (this.FormattedValues.Contains("type"))
				{
					return this.FormattedValues["type"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("valueschema")]
		public string ValueSchema
		{
			get
			{
				return this.GetAttributeValue<string>("valueschema");
			}
			set
			{
				this.OnPropertyChanging("ValueSchema");
				this.SetAttributeValue("valueschema", value);
				this.OnPropertyChanged("ValueSchema");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N envdefinition_envdefinition
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("envdefinition_envdefinition", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<Plugins.Models.EnvironmentVariableDefinition> Referencedenvdefinition_envdefinition
		{
			get
			{
				return this.GetRelatedEntities<Plugins.Models.EnvironmentVariableDefinition>("envdefinition_envdefinition", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencedenvdefinition_envdefinition");
				this.SetRelatedEntities<Plugins.Models.EnvironmentVariableDefinition>("envdefinition_envdefinition", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedenvdefinition_envdefinition");
			}
		}
		
		/// <summary>
		/// 1:N environmentvariabledefinition_environmentvariablevalue
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("environmentvariabledefinition_environmentvariablevalue")]
		public System.Collections.Generic.IEnumerable<Plugins.Models.EnvironmentVariableValue> environmentvariabledefinition_environmentvariablevalue
		{
			get
			{
				return this.GetRelatedEntities<Plugins.Models.EnvironmentVariableValue>("environmentvariabledefinition_environmentvariablevalue", null);
			}
			set
			{
				this.OnPropertyChanging("environmentvariabledefinition_environmentvariablevalue");
				this.SetRelatedEntities<Plugins.Models.EnvironmentVariableValue>("environmentvariabledefinition_environmentvariablevalue", null, value);
				this.OnPropertyChanged("environmentvariabledefinition_environmentvariablevalue");
			}
		}
		
		/// <summary>
		/// N:1 envdefinition_envdefinition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentdefinitionid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("envdefinition_envdefinition", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public Plugins.Models.EnvironmentVariableDefinition Referencingenvdefinition_envdefinition
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.EnvironmentVariableDefinition>("envdefinition_envdefinition", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingenvdefinition_envdefinition");
				this.SetRelatedEntity<Plugins.Models.EnvironmentVariableDefinition>("envdefinition_envdefinition", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingenvdefinition_envdefinition");
			}
		}
		
		/// <summary>
		/// N:1 lk_environmentvariabledefinition_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_environmentvariabledefinition_createdby")]
		public Plugins.Models.SystemUser lk_environmentvariabledefinition_createdby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_environmentvariabledefinition_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_environmentvariabledefinition_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_environmentvariabledefinition_createdonbehalfby")]
		public Plugins.Models.SystemUser lk_environmentvariabledefinition_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_environmentvariabledefinition_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_environmentvariabledefinition_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_environmentvariabledefinition_modifiedby")]
		public Plugins.Models.SystemUser lk_environmentvariabledefinition_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_environmentvariabledefinition_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_environmentvariabledefinition_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_environmentvariabledefinition_modifiedonbehalfby")]
		public Plugins.Models.SystemUser lk_environmentvariabledefinition_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_environmentvariabledefinition_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 team_environmentvariabledefinition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_environmentvariabledefinition")]
		public Plugins.Models.Team team_environmentvariabledefinition
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Team>("team_environmentvariabledefinition", null);
			}
		}
		
		/// <summary>
		/// N:1 user_environmentvariabledefinition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_environmentvariabledefinition")]
		public Plugins.Models.SystemUser user_environmentvariabledefinition
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("user_environmentvariabledefinition", null);
			}
		}
	}
}
#pragma warning restore CS1591
