#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_msfp_survey_msdyn_mcsbotstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 357890000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ready = 357890001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disconnected = 357890002,
	}
	
	/// <summary>
	/// Status of the Customer Voice survey.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msfp_survey_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Customer Voice survey.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msfp_survey_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 100000002,
	}
	
	/// <summary>
	/// Set of questions to collect feedback.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msfp_survey")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class msfp_survey : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the msfp_survey entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string msdyn_mcsbotstatus = "msdyn_mcsbotstatus";
			public const string msdyn_mcsbotstatusName = "msdyn_mcsbotstatusname";
			public const string msdyn_microsoftcopilotstudiobot = "msdyn_microsoftcopilotstudiobot";
			public const string msdyn_microsoftcopilotstudiobotName = "msdyn_microsoftcopilotstudiobotname";
			public const string msdyn_surveyprovider = "msdyn_surveyprovider";
			public const string msdyn_surveyproviderName = "msdyn_surveyprovidername";
			public const string msfp_acceptanonymousresponses = "msfp_acceptanonymousresponses";
			public const string msfp_acceptanonymousresponsesName = "msfp_acceptanonymousresponsesname";
			public const string msfp_anonymousurl = "msfp_anonymousurl";
			public const string msfp_description = "msfp_description";
			public const string msfp_embedcode = "msfp_embedcode";
			public const string msfp_enddate = "msfp_enddate";
			public const string msfp_friendlyname = "msfp_friendlyname";
			public const string msfp_latestsurveyidentifier = "msfp_latestsurveyidentifier";
			public const string msfp_name = "msfp_name";
			public const string msfp_otherproperties = "msfp_otherproperties";
			public const string msfp_PermanentID = "msfp_permanentid";
			public const string msfp_project = "msfp_project";
			public const string msfp_projectName = "msfp_projectname";
			public const string msfp_publishedby = "msfp_publishedby";
			public const string msfp_publishedbyName = "msfp_publishedbyname";
			public const string msfp_publishedbyYomiName = "msfp_publishedbyyominame";
			public const string msfp_publishedon = "msfp_publishedon";
			public const string msfp_sourcesurveyidentifier = "msfp_sourcesurveyidentifier";
			public const string msfp_sourcesurveymodifieddate = "msfp_sourcesurveymodifieddate";
			public const string msfp_sourcesurveyversion = "msfp_sourcesurveyversion";
			public const string msfp_startdate = "msfp_startdate";
			public const string msfp_surveyId = "msfp_surveyid";
			public const string Id = "msfp_surveyid";
			public const string msfp_surveysource = "msfp_surveysource";
			public const string msfp_surveytableid = "msfp_surveytableid";
			public const string msfp_surveyurl = "msfp_surveyurl";
			public const string msfp_variables = "msfp_variables";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string cm_checklistmaster_Survey_msfp_survey = "cm_checklistmaster_Survey_msfp_survey";
			public const string msfp_msfp_survey_msfp_surveyinvite_surveyid = "msfp_msfp_survey_msfp_surveyinvite_surveyid";
			public const string lk_msfp_survey_createdby = "lk_msfp_survey_createdby";
			public const string lk_msfp_survey_createdonbehalfby = "lk_msfp_survey_createdonbehalfby";
			public const string lk_msfp_survey_modifiedby = "lk_msfp_survey_modifiedby";
			public const string lk_msfp_survey_modifiedonbehalfby = "lk_msfp_survey_modifiedonbehalfby";
			public const string msfp_msfp_project_msfp_survey_project = "msfp_msfp_project_msfp_survey_project";
			public const string msfp_systemuser_msfp_survey_publishedby = "msfp_systemuser_msfp_survey_publishedby";
			public const string team_msfp_survey = "team_msfp_survey";
			public const string user_msfp_survey = "user_msfp_survey";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public msfp_survey() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msfp_survey";
		
		public const string EntityLogicalCollectionName = "msfp_surveies";
		
		public const string EntitySetName = "msfp_surveies";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// MCS Bot Status
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_mcsbotstatus")]
		public virtual msdyn_msfp_survey_msdyn_mcsbotstatus? msdyn_mcsbotstatus
		{
			get
			{
				return ((msdyn_msfp_survey_msdyn_mcsbotstatus?)(EntityOptionSetEnum.GetEnum(this, "msdyn_mcsbotstatus")));
			}
			set
			{
				this.OnPropertyChanging("msdyn_mcsbotstatus");
				this.SetAttributeValue("msdyn_mcsbotstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdyn_mcsbotstatus");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_mcsbotstatusname")]
		public string msdyn_mcsbotstatusName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_mcsbotstatus"))
				{
					return this.FormattedValues["msdyn_mcsbotstatus"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_microsoftcopilotstudiobot")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_microsoftcopilotstudiobot
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_microsoftcopilotstudiobot");
			}
			set
			{
				this.OnPropertyChanging("msdyn_microsoftcopilotstudiobot");
				this.SetAttributeValue("msdyn_microsoftcopilotstudiobot", value);
				this.OnPropertyChanged("msdyn_microsoftcopilotstudiobot");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_microsoftcopilotstudiobotname")]
		public string msdyn_microsoftcopilotstudiobotName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_microsoftcopilotstudiobot"))
				{
					return this.FormattedValues["msdyn_microsoftcopilotstudiobot"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_surveyprovider")]
		public virtual msdyn_surveyprovider? msdyn_surveyprovider
		{
			get
			{
				return ((msdyn_surveyprovider?)(EntityOptionSetEnum.GetEnum(this, "msdyn_surveyprovider")));
			}
			set
			{
				this.OnPropertyChanging("msdyn_surveyprovider");
				this.SetAttributeValue("msdyn_surveyprovider", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdyn_surveyprovider");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_surveyprovidername")]
		public string msdyn_surveyproviderName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_surveyprovider"))
				{
					return this.FormattedValues["msdyn_surveyprovider"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Specifies if responses can be accepted from anonymous respondents.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_acceptanonymousresponses")]
		public System.Nullable<bool> msfp_acceptanonymousresponses
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msfp_acceptanonymousresponses");
			}
			set
			{
				this.OnPropertyChanging("msfp_acceptanonymousresponses");
				this.SetAttributeValue("msfp_acceptanonymousresponses", value);
				this.OnPropertyChanged("msfp_acceptanonymousresponses");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_acceptanonymousresponsesname")]
		public string msfp_acceptanonymousresponsesName
		{
			get
			{
				if (this.FormattedValues.Contains("msfp_acceptanonymousresponses"))
				{
					return this.FormattedValues["msfp_acceptanonymousresponses"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Link to the anonymous survey response.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_anonymousurl")]
		public string msfp_anonymousurl
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_anonymousurl");
			}
			set
			{
				this.OnPropertyChanging("msfp_anonymousurl");
				this.SetAttributeValue("msfp_anonymousurl", value);
				this.OnPropertyChanged("msfp_anonymousurl");
			}
		}
		
		/// <summary>
		/// Description of the survey.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_description")]
		public string msfp_description
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_description");
			}
			set
			{
				this.OnPropertyChanging("msfp_description");
				this.SetAttributeValue("msfp_description", value);
				this.OnPropertyChanged("msfp_description");
			}
		}
		
		/// <summary>
		/// Embed code for the survey
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_embedcode")]
		public string msfp_embedcode
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_embedcode");
			}
			set
			{
				this.OnPropertyChanging("msfp_embedcode");
				this.SetAttributeValue("msfp_embedcode", value);
				this.OnPropertyChanged("msfp_embedcode");
			}
		}
		
		/// <summary>
		/// End date and time of the survey, if configured.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_enddate")]
		public System.Nullable<System.DateTime> msfp_enddate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msfp_enddate");
			}
			set
			{
				this.OnPropertyChanging("msfp_enddate");
				this.SetAttributeValue("msfp_enddate", value);
				this.OnPropertyChanged("msfp_enddate");
			}
		}
		
		/// <summary>
		/// Friendly name of the survey.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_friendlyname")]
		public string msfp_friendlyname
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_friendlyname");
			}
			set
			{
				this.OnPropertyChanging("msfp_friendlyname");
				this.SetAttributeValue("msfp_friendlyname", value);
				this.OnPropertyChanged("msfp_friendlyname");
			}
		}
		
		/// <summary>
		/// Latest identifier for the survey.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_latestsurveyidentifier")]
		public string msfp_latestsurveyidentifier
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_latestsurveyidentifier");
			}
			set
			{
				this.OnPropertyChanging("msfp_latestsurveyidentifier");
				this.SetAttributeValue("msfp_latestsurveyidentifier", value);
				this.OnPropertyChanged("msfp_latestsurveyidentifier");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_name")]
		public string msfp_name
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_name");
			}
			set
			{
				this.OnPropertyChanging("msfp_name");
				this.SetAttributeValue("msfp_name", value);
				this.OnPropertyChanged("msfp_name");
			}
		}
		
		/// <summary>
		/// Other survey properties in JSON format.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_otherproperties")]
		public string msfp_otherproperties
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_otherproperties");
			}
			set
			{
				this.OnPropertyChanging("msfp_otherproperties");
				this.SetAttributeValue("msfp_otherproperties", value);
				this.OnPropertyChanged("msfp_otherproperties");
			}
		}
		
		/// <summary>
		/// Permanent ID is auto-generated for a new survey. For a copied survey, the ID is carried over from the original survey.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_permanentid")]
		public string msfp_PermanentID
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_permanentid");
			}
			set
			{
				this.OnPropertyChanging("msfp_PermanentID");
				this.SetAttributeValue("msfp_permanentid", value);
				this.OnPropertyChanged("msfp_PermanentID");
			}
		}
		
		/// <summary>
		/// Project associated with the survey.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_project")]
		public Microsoft.Xrm.Sdk.EntityReference msfp_project
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msfp_project");
			}
			set
			{
				this.OnPropertyChanging("msfp_project");
				this.SetAttributeValue("msfp_project", value);
				this.OnPropertyChanged("msfp_project");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_projectname")]
		public string msfp_projectName
		{
			get
			{
				if (this.FormattedValues.Contains("msfp_project"))
				{
					return this.FormattedValues["msfp_project"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// User who published the survey.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_publishedby")]
		public Microsoft.Xrm.Sdk.EntityReference msfp_publishedby
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msfp_publishedby");
			}
			set
			{
				this.OnPropertyChanging("msfp_publishedby");
				this.SetAttributeValue("msfp_publishedby", value);
				this.OnPropertyChanged("msfp_publishedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_publishedbyname")]
		public string msfp_publishedbyName
		{
			get
			{
				if (this.FormattedValues.Contains("msfp_publishedby"))
				{
					return this.FormattedValues["msfp_publishedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_publishedbyyominame")]
		public string msfp_publishedbyYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("msfp_publishedby"))
				{
					return this.FormattedValues["msfp_publishedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time on which the survey was published.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_publishedon")]
		public System.Nullable<System.DateTime> msfp_publishedon
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msfp_publishedon");
			}
			set
			{
				this.OnPropertyChanging("msfp_publishedon");
				this.SetAttributeValue("msfp_publishedon", value);
				this.OnPropertyChanged("msfp_publishedon");
			}
		}
		
		/// <summary>
		/// Unique identifier for the survey in the source application.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_sourcesurveyidentifier")]
		public string msfp_sourcesurveyidentifier
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_sourcesurveyidentifier");
			}
			set
			{
				this.OnPropertyChanging("msfp_sourcesurveyidentifier");
				this.SetAttributeValue("msfp_sourcesurveyidentifier", value);
				this.OnPropertyChanged("msfp_sourcesurveyidentifier");
			}
		}
		
		/// <summary>
		/// Date when a survey is modified in source.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_sourcesurveymodifieddate")]
		public System.Nullable<System.DateTime> msfp_sourcesurveymodifieddate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msfp_sourcesurveymodifieddate");
			}
			set
			{
				this.OnPropertyChanging("msfp_sourcesurveymodifieddate");
				this.SetAttributeValue("msfp_sourcesurveymodifieddate", value);
				this.OnPropertyChanged("msfp_sourcesurveymodifieddate");
			}
		}
		
		/// <summary>
		/// Version number of the survey.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_sourcesurveyversion")]
		public string msfp_sourcesurveyversion
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_sourcesurveyversion");
			}
			set
			{
				this.OnPropertyChanging("msfp_sourcesurveyversion");
				this.SetAttributeValue("msfp_sourcesurveyversion", value);
				this.OnPropertyChanged("msfp_sourcesurveyversion");
			}
		}
		
		/// <summary>
		/// Start date and time of the survey, if configured.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_startdate")]
		public System.Nullable<System.DateTime> msfp_startdate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msfp_startdate");
			}
			set
			{
				this.OnPropertyChanging("msfp_startdate");
				this.SetAttributeValue("msfp_startdate", value);
				this.OnPropertyChanged("msfp_startdate");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_surveyid")]
		public System.Nullable<System.Guid> msfp_surveyId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msfp_surveyid");
			}
			set
			{
				this.OnPropertyChanging("msfp_surveyId");
				this.SetAttributeValue("msfp_surveyid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msfp_surveyId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_surveyid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.msfp_surveyId = value;
			}
		}
		
		/// <summary>
		/// Source through which the survey was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_surveysource")]
		public string msfp_surveysource
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_surveysource");
			}
			set
			{
				this.OnPropertyChanging("msfp_surveysource");
				this.SetAttributeValue("msfp_surveysource", value);
				this.OnPropertyChanged("msfp_surveysource");
			}
		}
		
		/// <summary>
		/// Customer Voice Survey Table Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_surveytableid")]
		public string msfp_surveytableid
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_surveytableid");
			}
			set
			{
				this.OnPropertyChanging("msfp_surveytableid");
				this.SetAttributeValue("msfp_surveytableid", value);
				this.OnPropertyChanged("msfp_surveytableid");
			}
		}
		
		/// <summary>
		/// Link to the survey in Customer Voice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_surveyurl")]
		public string msfp_surveyurl
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_surveyurl");
			}
			set
			{
				this.OnPropertyChanging("msfp_surveyurl");
				this.SetAttributeValue("msfp_surveyurl", value);
				this.OnPropertyChanged("msfp_surveyurl");
			}
		}
		
		/// <summary>
		/// Stores survey variables and their default values in JSON format.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_variables")]
		public string msfp_variables
		{
			get
			{
				return this.GetAttributeValue<string>("msfp_variables");
			}
			set
			{
				this.OnPropertyChanging("msfp_variables");
				this.SetAttributeValue("msfp_variables", value);
				this.OnPropertyChanged("msfp_variables");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Survey
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual msfp_survey_statecode? statecode
		{
			get
			{
				return ((msfp_survey_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Survey
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual msfp_survey_statuscode? statuscode
		{
			get
			{
				return ((msfp_survey_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N cm_checklistmaster_Survey_msfp_survey
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cm_checklistmaster_Survey_msfp_survey")]
		public System.Collections.Generic.IEnumerable<Plugins.Models.cm_ChecklistMaster> cm_checklistmaster_Survey_msfp_survey
		{
			get
			{
				return this.GetRelatedEntities<Plugins.Models.cm_ChecklistMaster>("cm_checklistmaster_Survey_msfp_survey", null);
			}
			set
			{
				this.OnPropertyChanging("cm_checklistmaster_Survey_msfp_survey");
				this.SetRelatedEntities<Plugins.Models.cm_ChecklistMaster>("cm_checklistmaster_Survey_msfp_survey", null, value);
				this.OnPropertyChanged("cm_checklistmaster_Survey_msfp_survey");
			}
		}
		
		/// <summary>
		/// 1:N msfp_msfp_survey_msfp_surveyinvite_surveyid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msfp_msfp_survey_msfp_surveyinvite_surveyid")]
		public System.Collections.Generic.IEnumerable<Plugins.Models.msfp_surveyinvite> msfp_msfp_survey_msfp_surveyinvite_surveyid
		{
			get
			{
				return this.GetRelatedEntities<Plugins.Models.msfp_surveyinvite>("msfp_msfp_survey_msfp_surveyinvite_surveyid", null);
			}
			set
			{
				this.OnPropertyChanging("msfp_msfp_survey_msfp_surveyinvite_surveyid");
				this.SetRelatedEntities<Plugins.Models.msfp_surveyinvite>("msfp_msfp_survey_msfp_surveyinvite_surveyid", null, value);
				this.OnPropertyChanged("msfp_msfp_survey_msfp_surveyinvite_surveyid");
			}
		}
		
		/// <summary>
		/// N:1 lk_msfp_survey_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msfp_survey_createdby")]
		public Plugins.Models.SystemUser lk_msfp_survey_createdby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_msfp_survey_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msfp_survey_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msfp_survey_createdonbehalfby")]
		public Plugins.Models.SystemUser lk_msfp_survey_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_msfp_survey_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msfp_survey_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msfp_survey_modifiedby")]
		public Plugins.Models.SystemUser lk_msfp_survey_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_msfp_survey_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msfp_survey_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msfp_survey_modifiedonbehalfby")]
		public Plugins.Models.SystemUser lk_msfp_survey_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("lk_msfp_survey_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 msfp_msfp_project_msfp_survey_project
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_project")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msfp_msfp_project_msfp_survey_project")]
		public Plugins.Models.msfp_project msfp_msfp_project_msfp_survey_project
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.msfp_project>("msfp_msfp_project_msfp_survey_project", null);
			}
			set
			{
				this.OnPropertyChanging("msfp_msfp_project_msfp_survey_project");
				this.SetRelatedEntity<Plugins.Models.msfp_project>("msfp_msfp_project_msfp_survey_project", null, value);
				this.OnPropertyChanged("msfp_msfp_project_msfp_survey_project");
			}
		}
		
		/// <summary>
		/// N:1 msfp_systemuser_msfp_survey_publishedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msfp_publishedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msfp_systemuser_msfp_survey_publishedby")]
		public Plugins.Models.SystemUser msfp_systemuser_msfp_survey_publishedby
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("msfp_systemuser_msfp_survey_publishedby", null);
			}
			set
			{
				this.OnPropertyChanging("msfp_systemuser_msfp_survey_publishedby");
				this.SetRelatedEntity<Plugins.Models.SystemUser>("msfp_systemuser_msfp_survey_publishedby", null, value);
				this.OnPropertyChanged("msfp_systemuser_msfp_survey_publishedby");
			}
		}
		
		/// <summary>
		/// N:1 team_msfp_survey
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_msfp_survey")]
		public Plugins.Models.Team team_msfp_survey
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.Team>("team_msfp_survey", null);
			}
		}
		
		/// <summary>
		/// N:1 user_msfp_survey
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_msfp_survey")]
		public Plugins.Models.SystemUser user_msfp_survey
		{
			get
			{
				return this.GetRelatedEntity<Plugins.Models.SystemUser>("user_msfp_survey", null);
			}
		}
	}
}
#pragma warning restore CS1591
