#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Plugins.Models
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_CaseCategory"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_CaseCategory> cm_CaseCategorySet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_CaseCategory>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_CaseChecklistCatalog"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_CaseChecklistCatalog> cm_CaseChecklistCatalogSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_CaseChecklistCatalog>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_CaseChecklistResponse"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_CaseChecklistResponse> cm_CaseChecklistResponseSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_CaseChecklistResponse>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_CaseSubCategory"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_CaseSubCategory> cm_CaseSubCategorySet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_CaseSubCategory>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_LeadClosureChecklistCatalog"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_LeadClosureChecklistCatalog> cm_LeadClosureChecklistCatalogSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_LeadClosureChecklistCatalog>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_LeadClosureChecklistMaster"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_LeadClosureChecklistMaster> cm_LeadClosureChecklistMasterSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_LeadClosureChecklistMaster>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_LeadClosureChecklistResponse"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_LeadClosureChecklistResponse> cm_LeadClosureChecklistResponseSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_LeadClosureChecklistResponse>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_ProgramAssociation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_ProgramAssociation> cm_ProgramAssociationSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_ProgramAssociation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_Province"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_Province> cm_ProvinceSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_Province>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_QuestionCatalog"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_QuestionCatalog> cm_QuestionCatalogSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_QuestionCatalog>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.cm_QuestionResponse"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.cm_QuestionResponse> cm_QuestionResponseSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.cm_QuestionResponse>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.Connection"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.Connection> ConnectionSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.Connection>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.Incident"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.Incident> IncidentSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.Incident>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.Lead"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.Lead> LeadSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.Lead>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.Opportunity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.Opportunity> OpportunitySet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.Opportunity>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.SalesOrder"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.SalesOrder> SalesOrderSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.SalesOrder>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Plugins.Models.Team"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Plugins.Models.Team> TeamSet
		{
			get
			{
				return this.CreateQuery<Plugins.Models.Team>();
			}
		}
	}
}
#pragma warning restore CS1591
